# Change these first
owner: desa-group # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: VAIN
    url: https://vain.rusz.dev
  - name: Matrix
    url: https://matrix.rusz.dev

assignees:
  - ethanrusz # Assign downtime issues to...

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: VAIN Status
  introTitle: "VAIN Project Status"
  introMessage: You can use this page to check the uptime of VAIN related pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://desa-group.github.io/status/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
